language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn test
after_success:
  - greenkeeper-lockfile-upload
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
